### PR TITLE
Issue #353: Enable anonymous access

### PR DESCRIPTION
**Pull request by cferbar**
I made a change in te application to enable access and reproduce videos without login.

The changes are:

- Added a setting to enable or disable the anonymous access. This settings control a user with "anonymous" username, to simulate the access without login (if check this setting and the user not exists or is disabled, the user is created or enabled. if disable the setting, the user is drop). This is because using Spring Security and the InterceptUrl, i can't add the anonymous access in that map (it can't be disable in execution easily)

- Added a special user called "anonymous" (commented in the previous point). In the user section in admin page, the changes in this user modify the "anonymous_access" setting. (if disable, delete or change the username, the setting is disabled, and if enable the user, the setting is enabled).

- Created a custom LoginController, mostly equal to the controller of the Spring Security Core plugin, but checking in the auth method if "anonymous_access" is enabled, to authenticate with the "anonymous user". Added a new method, called login(), to do the authentication in that case. This method is called from the header of the anonymous user. This header have a button to authenticate user, instead of the dropdown menu for the authenticated user.

- Created a custom header for the anonymous access, with a button to login into the application, and a new function in angular to do the redirect to the login page.

Another options for this issue could be:

- Add a boolean field in the user model, to mark the anonymous user in this field, and not check the username

- Change the InterceptUrl dynamically, to add or remove the anonymous rules.

### CODE REVIEW

**Comment by Jeronimo95** [comment]
@cferbar This is great! I've merged it with my fork. Jeronimo95/streama#2

**Comment by diyarit** [comment]
how I can use these changes without removing the app ? can you point the files you have changed

**Comment by Jeronimo95** [comment]
My branch is (well should be) database compatible with this one. Clone and checkout my dev branch and assemble the WAR, backup your database (just in case), then copy the new WAR over your current one.

(If you just want to see the files changed on this pull, click "Files Changed" at the top)

**Comment by diyarit** [comment]
can I replace the files that has been modified ?

**Comment by Jeronimo95** [comment]
I guess? You still would have to compile it.

**Comment by Jeronimo95** [comment]
@diyarit I'm not going to login to you server and do it for you. If you don't want to compile it you'll have to wait until I build a release version of my fork. No ETA on the currently.

**Comment by dularion** [comment]
Fantastic! will merge and make a beta release now

**Comment by diyarit** [comment]
add more stuff XD

**Pull request merged**
