### PR TITLE
Add local files to videos

### PR DESCRIPTION
**Pull request by jendib**

### CODE REVIEW

**Comment by dularion** [comment]
Wow thank you!
I'll be checking this out later and take a look at it locally before I merge but great work!!

**Comment by dularion** [comment]
I've played around with it a bit now and am suggesting a few tweaks:
- as long as the setting for local video directory isn't filled in the tab should either not show up in the manage file modal or a little notice should be displayed for the users with a link to the settings page. 
-when choosing a file, the name is the entire file path. I'd split by / and only use the last item, or maybe easier with Java io file, use the file name only. 
- removing the file from the episode / movie actually deletes it from hard-drive. I think that functionality makes sense with uploaded files, but in the case of this feature I'd stop at removing it from db. 

Either I can fix these issues or you, you choose :) but I probably won't get to it soon as I'm swamped right now. 

Great work!!! Thanks for your contribution!

**Comment by jendib** [comment]
It's all done!

**Comment by dularion** [comment]
Youre a machine!! 👍

**Pull request merged**
