### PR TITLE
Fixes dularion/streama#195

### PR DESCRIPTION
**Pull request by gkiko**
Return after first redirect

### CODE REVIEW

**Comment by dularion** [comment]
Thanks mate!

**Comment by gkiko** [comment]
Do you know why builds on grails 3 fail on travis ci? Should I investigate?

**Comment by dularion** [comment]
Yea I know why, it's because it's running the tests as though it's a grails 2 project. 
./grailsw: No such file or directory

Not sure how to tell it to treat one branch differently ... Feel free to investigate!

**Comment by gkiko** [comment]
Both branches will have their own `.travis.yml`

**Comment by dularion** [comment]
Oh right!! True 😅 if you want you can try to adjust it

**Pull request merged**
